"""add source_type to documents

Revision ID: ebe87f8e65b4
Revises: a62198cc4109
Create Date: 2026-08-20 18:54:15.259116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe87f8e65b4'
down_revision: Union[str, None] = 'a62198cc4109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'source_type')
    # ### end Alembic commands ###
