"""add analysis_runs (M4) and finding grading/applicability columns (M5)

M4 — analysis_runs makes an Analyze a record instead of an untracked event: which
document versions were read, which prompt and model produced the results, what it
cost, and whether the auditor accepted coverage that was incomplete.
evidence_mappings.run_id is promoted to a real foreign key here.

M5 — findings gain the grading a certification body actually issues, replacing the
invented 70/30 -> met/partial/gap rubric, plus applicability for Annex A controls
only (clauses can never be excluded, so is_applicable stays NULL for them).

Revision ID: f5a6b7c8d9e0
Revises: e4f5a6b7c8d9
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f5a6b7c8d9e0"
down_revision: Union[str, None] = "e4f5a6b7c8d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

GRADE_VALUES = "('conforming', 'ofi', 'minor_nc', 'major_nc', 'not_applicable')"


def upgrade() -> None:
    # ---------------- M4: analysis_runs ----------------
    op.create_table(
        "analysis_runs",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("certification_standard", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="running"),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("triggered_by", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("document_ids", postgresql.ARRAY(postgresql.UUID(as_uuid=True)), nullable=True),
        sa.Column("prompt_version_clause", sa.String(length=60), nullable=True),
        sa.Column("prompt_version_control", sa.String(length=60), nullable=True),
        sa.Column("model_id", sa.String(length=80), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("cached_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("gate_accepted_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("gate_accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gate_override_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"]),
        sa.ForeignKeyConstraint(["triggered_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["gate_accepted_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "status IN ('running', 'coverage_ready', 'accepted', 'failed')", name="ck_analysis_runs_status"
        ),
    )
    op.create_index(
        "ix_analysis_runs_org_standard",
        "analysis_runs",
        ["organization_id", "certification_standard", "started_at"],
    )

    # evidence_mappings.run_id predates this table (M2 wrote plain UUIDs). Any rows
    # from before now point at runs that were never recorded, so they can't be given
    # a valid FK — clear them rather than leave dangling references. They're
    # regenerated by the next Analyze.
    op.execute("DELETE FROM evidence_mappings")
    op.create_foreign_key(
        "fk_evidence_mappings_run_id", "evidence_mappings", "analysis_runs", ["run_id"], ["id"], ondelete="CASCADE"
    )

    # ---------------- M5: grading + applicability ----------------
    op.add_column("findings", sa.Column("analysis_run_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(
        "fk_findings_analysis_run_id", "findings", "analysis_runs", ["analysis_run_id"], ["id"], ondelete="SET NULL"
    )

    # Annex A controls only. NULL for clauses 4-10, which can never be excluded —
    # enforced by the check constraint below rather than left to application code.
    op.add_column("findings", sa.Column("is_applicable", sa.Boolean(), nullable=True))
    op.add_column("findings", sa.Column("applicability_note", sa.Text(), nullable=True))

    op.add_column("findings", sa.Column("proposed_grade", sa.String(length=20), nullable=True))
    op.add_column("findings", sa.Column("grade", sa.String(length=20), nullable=True))
    op.create_check_constraint(
        "ck_findings_proposed_grade", "findings", f"proposed_grade IS NULL OR proposed_grade IN {GRADE_VALUES}"
    )
    op.create_check_constraint("ck_findings_grade", "findings", f"grade IS NULL OR grade IN {GRADE_VALUES}")
    # An exclusion without a stated reason is not an exclusion an auditor can defend.
    op.create_check_constraint(
        "ck_findings_exclusion_needs_note",
        "findings",
        "is_applicable IS DISTINCT FROM false OR applicability_note IS NOT NULL",
    )

    # A confirmed finding whose backing evidence later changed must be visible as
    # such, rather than silently keeping an answer that no longer matches the
    # documents (see crud/finding.py — both write paths used to skip reviewed rows).
    op.add_column(
        "findings",
        sa.Column("evidence_changed_since_review", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )


def downgrade() -> None:
    op.drop_column("findings", "evidence_changed_since_review")
    op.drop_constraint("ck_findings_exclusion_needs_note", "findings", type_="check")
    op.drop_constraint("ck_findings_grade", "findings", type_="check")
    op.drop_constraint("ck_findings_proposed_grade", "findings", type_="check")
    op.drop_column("findings", "grade")
    op.drop_column("findings", "proposed_grade")
    op.drop_column("findings", "applicability_note")
    op.drop_column("findings", "is_applicable")
    op.drop_constraint("fk_findings_analysis_run_id", "findings", type_="foreignkey")
    op.drop_column("findings", "analysis_run_id")

    op.drop_constraint("fk_evidence_mappings_run_id", "evidence_mappings", type_="foreignkey")

    op.drop_index("ix_analysis_runs_org_standard", table_name="analysis_runs")
    op.drop_table("analysis_runs")
